### ISSUE TITLE
Ubuntu 22.04 support

### ISSUE THREAD

**Issue by shuhaowu** [ros-realtime/linux-real-time-kernel-builder#36]
Ubuntu 22.04 is out, but it seems like it has a PREEMPT_RT kernel already precompiled? See https://ubuntu.com/engage/an-introduction-to-real-time-linux-part-i

cc: @carlossvg @LanderU @razr

**Comment by shuhaowu** [comment]
It seems like the RT kernel is only available if you subscribe to Canonical's "Ubuntu Advantage" (with an exemption for personal use). So it seems like we probably still have to build our own kernel for this.

**Comment by razr** [comment]
Even if it is precompiled it is probably a generic ARM64 kernel and we need to rebuild it for RPI4. The only advantage I see is that it is integrated with an RT_PREEMPT patch. I couldn't find any git reference to it https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/

**Comment by shuhaowu** [comment]
Yeah I think we can probably use the existing system to patch the kernel for 22.04 and build our own Debian package.

**Comment by razr** [comment]
I have built the RPI4 kernel for Ubuntu 22.04:

```
docker build --build-arg UBUNTU_VERSION=jammy --build-arg KERNEL_VERSION=5.15.0 --build-arg LTTNG_VERSION=2.13 -t rtwg-image-22.04 .
docker run -ti rtwg-image-22.04
cd $HOME/linux_build/linux-raspi
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LOCALVERSION=-raspi -j `nproc` bindeb-pkg
```

then I have updated my RPI4 to ubuntu 22.04:

```
sudo apt-get update
sudo apt-get upgrade

# 20.04 -> 22.04
sudo sed -i 's/focal/jammy/g' /etc/apt/sources.list

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get autoremove
sudo apt-get clean
```
copied and installed `deb`

```
ubuntu@ubuntu:~$ ls
linux-headers-5.15.30-rt38-raspi_5.15.30-rt38-raspi-1_arm64.deb  linux-libc-dev_5.15.30-rt38-raspi-1_arm64.deb
linux-image-5.15.30-rt38-raspi_5.15.30-rt38-raspi-1_arm64.deb
ubuntu@ubuntu:~$ sudo dpkg -i *.deb
```

```
ubuntu@ubuntu:~$ sudo reboot
ubuntu@ubuntu:~$ uname -r
5.15.30-rt38-raspi
```

@LanderU if you can review and merge my updated [PR](https://github.com/ros-realtime/linux-real-time-kernel-builder/pull/35), I can add a job to build a kernel for 22.04

**Comment by carlossvg** [comment]
@shuhaowu @razr @LanderU https://github.com/ros-realtime/linux-real-time-kernel-builder/pull/35 has been merged. This issue should be unblocked now. This would allow us to add support for humble and rolling now.

**Comment by nexus1203** [comment]
@razr @LanderU the kernel build was failed. Is there is an update on this? I really appreciate the great work.

**Comment by LanderU** [comment]
@nexus1203, sorry, I've re-run the jobs, if they fail I need to review why.

**Comment by LanderU** [comment]
@nexus1203, https://github.com/ros-realtime/linux-real-time-kernel-builder/actions/runs/2681210749 would you check if the release from this job works for you? Thanks!
