### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by jrutgeer** [ros-realtime/linux-real-time-kernel-builder#45]
Hi, 

I get following error during the "Build a Linux Real-Time kernel using docker" procedure:

<pre>
user@5179afff0dbc:~/linux_build/linux-raspi$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bindeb-pkg
sh ./scripts/package/mkdebian
dpkg-buildpackage -r"fakeroot -u" -a$(cat debian/arch)  -b -nc -uc
dpkg-buildpackage: info: source package linux-5.4.218-rt79+
dpkg-buildpackage: info: source version 5.4.218-rt79+-1
dpkg-buildpackage: info: source distribution focal
dpkg-buildpackage: info: source changed by user <user@5179afff0dbc>
dpkg-buildpackage: info: host architecture arm64
 dpkg-source --before-build .
dpkg-source: info: using options from linux-raspi/debian/source/options: --extend-diff-ignore=^arch/arm64/boot/dts/broadcom/bcm283x-rpi-csi1-2lane.dtsi$ --extend-diff-ignore=^arch/arm64/boot/dts/broadcom/bcm283x-rpi-lan7515.dtsi$ --extend-diff-ignore=^arch/arm64/boot/dts/overlays$ --diff-ignore --tar-ignore
 debian/rules build
make KERNELRELEASE=5.4.218-rt79+ ARCH=arm64 	KBUILD_BUILD_VERSION=1 -f ./Makefile
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      lttng/probes/lttng-probe-random.o
<b>lttng/probes/lttng-probe-random.c:18:10: fatal error: trace/events/random.h: No such file or directory
   18 | #include &lt;trace/events/random.h&gt;
      |          ^~~~~~~~~~~~~~~~~~~~~~~</b>
compilation terminated.
make[5]: *** [scripts/Makefile.build:270: lttng/probes/lttng-probe-random.o] Error 1
make[4]: *** [scripts/Makefile.build:519: lttng/probes] Error 2
make[3]: *** [Makefile:1768: lttng] Error 2
make[2]: *** [debian/rules:6: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:83: bindeb-pkg] Error 2
make: *** [Makefile:1503: bindeb-pkg] Error 2
</pre>

**Comment by razr** [comment]
Thanks for reporting it. I can confirm it, It looks like there is some incompatibility between LTTNG 2.12 and the recent kernel versions, see [#3927](https://patchwork.yoctoproject.org/project/oe-core/patch/20220625223936.135521-1-marex@denx.de/#3927). I do not plan to fix 2.12 rather move to the 2.13 version which builds fine. Please use 

```bash
docker build --build-arg LTTNG_VERSION=2.13 -t rtwg-image .
```

I'll update a default version accordingly
