### ISSUE TITLE
lttng bug on ubuntu raspi kernel 5.4.0 with lttng ver 2.12

### ISSUE THREAD

**Issue by AltinayGrass** [ros-realtime/linux-real-time-kernel-builder#48]
Hello,

I get the following error when trying to build the kernel. Is it normal?

![Screenshot from 2023-02-06 19-32-06](https://user-images.githubusercontent.com/97592357/217029220-0f6d35d5-d465-4895-ad7a-c9bf34f94471.png)

Container builded with below command.

`docker build --no-cache --build-arg UBUNTU_VERSION=focal --build-arg KERNEL_VERSION=5.4.0 --build-arg UNAME_R=5.4.0-1079-raspi --build-arg RT_PATCH=5.4.221-rt79 --build-arg LTTNG_VERSION=2.12 -t rtwg-image .`

**Comment by razr** [comment]
@AltinayGrass what config option do you use for the `igh ethercat master`?
`lttng` is configured to be a part of the build. However, you can disable it by setting in the `.config-fragment`
```bash
# CONFIG_LTTNG is not set
```

**Comment by AltinayGrass** [comment]
`./configure --sysconfdir=/etc --enable-8139too=no --enable-hrtimer=yes`

`make all modules`

last command giving;

`/bin/sh: 1: scripts/basic/fixdep: Exec format error `

to handle this, I run below commands ; 

```
cd /usr/src/linux-headers-5.4.224-rt80-raspi/
sudo make oldconfig
sudo make prepare

```

**Comment by razr** [comment]
I have seen your post here https://gitlab.com/etherlab.org/ethercat/-/issues/39
To understand whether there is something missing while installing kernel deb packages or there is a problem with `RT_PREEMPT` patches you might probably first build `ethercat` modules natively on raspberry pi using stock Ubuntu kernel.

**Comment by AltinayGrass** [comment]
Is this the way to run ethercat on docker? Good idea, if it  works. I will try. 
But I installed *.deb files to raspi4.  I tried to build and install ethercat after rebooting with newly installed kernel. 
I have been  installed ethercat on untouched ubuntu focal 20.04 which has kernel 5.4.0.1080, it works. 
May be debian package creation is not work well 100%.

**Comment by razr** [comment]
yes, to build it using docker. I don't like to pollute my target with dev tools.
