### ISSUE TITLE
Create ROS distro branches

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/linux-real-time-kernel-builder#5]
- [ ] Remove master
- [ ] Create rolling and foxy branches

**Comment by carlossvg** [comment]
@razr @LanderU I think this won't be necessary in this repository. We will simply generate releases for specific kernel versions. It's up to https://github.com/ros-realtime/ros-realtime-rpi4-image to pick the correct one for each ROS distro. Please close the issue if you agree.

**Comment by LanderU** [comment]
+1

**Comment by razr** [comment]
+1, moreover, there is only possible to start a workflow on the default branch
