### ISSUE TITLE
Is it working also with older version of Raspberry?

### ISSUE THREAD

**Issue by mataruzz** [ros-realtime/linux-real-time-kernel-builder#51]
Hello,
I'm starting doing my little project using ROS2 (humble) to control motor, servo motors, etc, on a Raspberry 3B+.

I have immediately noticed that using a general kernel, I have jitter on the controller of my micro servo motor. So, I wonder if it is possible  reduce/remove this jitter, which is pretty annoying, using a RT kernel.

In case it is physically impossible, is there any way to have a more stable scheduler to have a more consistent PWM signal ?

**Comment by razr** [comment]
Hello @mataruzz 
it looks to me that the [Ubuntu Server](https://ubuntu.com/download/raspberry-pi) (including kernel) supports Raspberry Pi 2/3/4.

**Comment by LanderU** [comment]
I think this is already answered here: https://github.com/ros-realtime/ros-realtime-rpi4-image/issues/70

**Comment by mataruzz** [comment]
Yes, I confirm it also works on Raspberry 3B+.

Thanks
